### ISSUE TITLE
Cores do projeto

### ISSUE THREAD

**Issue by VictorHVasquez** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local#11]
Definir as cores do projeto

**Comment by VictorHVasquez** [comment]
@PedroHNunesAlves e @WesneyAndrade 
Por favor postem as cores aqui com o código RGB delas

**Comment by PedroHNunesAlves** [comment]
LawnGreen: #7CFC00 ou (124,252,0) -> Verde Claro
GoldenRod: #DAA520 ou (218,165,32) -> Amarelo
Gainsboro: #DCDCDC ou (220,220,220) -> Cinza Claro
Teal: #008080 ou (0,128,128) -> Azul turquesa escuro
LightSeaGreen: #20B2AA ou (32,178,170) - Azul turquesa claro
Marrom: #552F13

**Comment by WesneyAndrade** [comment]
Essas cores ficaram ótimas!

**Comment by PedroHNunesAlves** [comment]
![image](https://user-images.githubusercontent.com/127517961/234681013-b4e33ad1-3584-4f82-bbef-2fae9db6a451.png)
