### ISSUE TITLE
Fórum

### ISSUE THREAD

**Issue by VictorHVasquez** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local#16]

**Comment by WesneyAndrade** [comment]
Fóruns feitos em uma primeira proposta, com cores e tons diversificados. Porém, estes fugiriam da proposta do projeto então resolvemos modifica-lo

**Comment by WesneyAndrade** [comment]
![Forum Página 1](https://user-images.githubusercontent.com/128436722/234137995-388665e0-dca2-472e-8cad-da413553b9dd.jpg)
![Forum Página 2](https://user-images.githubusercontent.com/128436722/234138000-28857ead-cc60-4d5b-81f9-3f63970eb97a.jpg)
![Forum Página 3](https://user-images.githubusercontent.com/128436722/234138002-ab4750d5-5a95-4778-ac18-702465f00152.jpg)
![Forum Página 4](https://user-images.githubusercontent.com/128436722/234138004-30a7eb84-8d19-4eb6-9ca0-9364a2c5e8ad.jpg)
![Forum Página 5](https://user-images.githubusercontent.com/128436722/234138008-fe77e292-52bd-47d4-8340-83e944a4ad13.jpg)

**Comment by WesneyAndrade** [comment]
Nas duas possibilidades anteriores foram notadas o uso de demasiadas cores então tentamos simplificar utilizando as paletas de cores definidas em conjunto com o grupo.

**Comment by WesneyAndrade** [comment]
![Forum Página 1](https://user-images.githubusercontent.com/128436722/234138197-a3548c0e-e52a-4f8c-80e6-e9247428e9e6.jpg)
![Forum Página 2](https://user-images.githubusercontent.com/128436722/234138202-89089074-e2c0-42d4-abce-70bf7925693c.jpg)
![Forum Página 3](https://user-images.githubusercontent.com/128436722/234138204-0034b548-a8c2-45b3-b70d-a283a50677c2.jpg)
![Forum Página 4](https://user-images.githubusercontent.com/128436722/234138207-0d437149-42e8-49b7-8b52-9b963a5cc603.jpg)
![Forum Página 5](https://user-images.githubusercontent.com/128436722/234138208-4acd4d56-d6eb-43e0-a0cc-f63f867e7003.jpg)

**Comment by WesneyAndrade** [comment]
Por fim definimos que este conjunto de cores faria melhor sentido com os demais elementos do projeto.

**Comment by WesneyAndrade** [comment]
![Image](https://user-images.githubusercontent.com/128436722/235374031-da08c930-05bf-4eac-a4ed-054d51fe40ca.jpg)
![Image](https://user-images.githubusercontent.com/128436722/235374033-e227cc3a-7263-4c6d-8a16-291a76302c1f.png)
![Image](https://user-images.githubusercontent.com/128436722/235374034-783e4c5f-ac67-441a-86d5-c746b976d113.png)
![Image](https://user-images.githubusercontent.com/128436722/235374032-e72b98ab-5dea-4e50-939a-13f761d11df1.png)
![Image](https://user-images.githubusercontent.com/128436722/235374035-e4dbb6c9-b822-4662-bc29-ec1536f1d003.png)
![Image](https://user-images.githubusercontent.com/128436722/235374036-b0e6e64b-7936-4f94-bf8f-6be8433af479.png)

Fórum estabelecido com cores mais neutras para melhor visualização por parte dos usuários.

**Comment by WesneyAndrade** [comment]
![Image](https://user-images.githubusercontent.com/128436722/235378200-801d2243-3089-46bd-aee1-3d6ce58ec9e9.png)
![Image](https://user-images.githubusercontent.com/128436722/235378199-3bd6b8c0-d7f3-49a3-bf13-3f02565cc739.png)
![Image](https://user-images.githubusercontent.com/128436722/235378202-a9c1958c-1e15-4da5-b15b-adbbfd116679.png)
![Image](https://user-images.githubusercontent.com/128436722/235378201-dda2ead6-d73f-41af-8ea6-2d6b32eb6470.png)
![Image](https://user-images.githubusercontent.com/128436722/235378203-5b34bfc9-f607-4133-9f70-63d69018c10e.png)
![Image](https://user-images.githubusercontent.com/128436722/235378204-9a48a570-6170-4bb4-ae48-385f1beba550.png)

Forum Final 2 para incluir ícones de engajamento e alteração em algumas cores do fórum
