### ISSUE TITLE
User Flow - Governança Local

### ISSUE THREAD

**Issue by PedroHNunesAlves** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local#18]
![Image](https://user-images.githubusercontent.com/127517961/232878835-7402297e-3377-4053-a313-27f2ac9e75bd.png)

https://www.figma.com/file/CJT6Du9IhwE1OxaraygGUO/Diagrama-de-fluxo?node-id=0%3A1&t=tqjNidvHxJCkeCIV-1

**Comment by ldenardin** [comment]
Fiquei com dúvida no fluxo ...................
