### ISSUE TITLE
Ícones utilizados

### ISSUE THREAD

**Issue by PedroHNunesAlves** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local#24]
Adicionar os ícones

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234734922-d18b065d-a405-4491-ba79-c90b4a8e44ce.png)

https://www.flaticon.com/br/icone-gratis/menu-aberto_4294414?term=menu&page=1&position=2&origin=search&related_id=4294414

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234735252-73b25de5-31fa-497a-a335-f0df4422e1cf.png)

https://www.flaticon.com/br/icone-gratis/botao-home_5974907?term=home&page=1&position=5&origin=search&related_id=5974907

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234735387-a9631e95-bf48-4af3-a990-c368ad585459.png)

https://www.flaticon.com/br/icone-gratis/botao-voltar_93634?term=voltar&page=1&position=2&origin=search&related_id=93634

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234735528-7b1f823c-95cd-44a9-a281-19c4634306be.png)

https://www.flaticon.com/br/icone-gratis/do-utilizador_8509176?term=pessoa&page=1&position=12&origin=search&related_id=8509176

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234735607-e59cff38-d67e-4d1b-a426-83455365fad9.png)

https://www.flaticon.com/br/icone-gratis/pessoas_3171593?term=pessoa&page=1&position=3&origin=search&related_id=3171593

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234735709-837aa6d6-f9a7-4588-9b85-30f31abe22e1.png)

https://www.flaticon.com/br/icone-gratis/lupa_2319177?term=lupa&page=1&position=1&origin=search&related_id=2319177

**Comment by lukaao** [comment]
![GL - PGN (1)](https://user-images.githubusercontent.com/112134718/234735939-7e71a594-769a-42b7-897e-99c0340e0137.png)
Logo

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234951279-05563307-fd89-4605-afa7-48e678a3de7a.png)

https://www.flaticon.com/br/icone-gratis/mapas-e-bandeiras_446075?term=mapa&page=1&position=8&origin=search&related_id=446075

**Comment by PedroHNunesAlves** [comment]
![Image](https://user-images.githubusercontent.com/127517961/234959722-b351f518-23ea-4d90-bce4-0227c61167f5.png)

<a href="https://www.flaticon.com/br/icones-gratis/resumo" title="resumo ícones">Resumo ícones criados por Freepik - Flaticon</a>

**Comment by GabrielASMm** [comment]
![Image](https://user-images.githubusercontent.com/102264520/234977685-b410a5f8-cb6c-4d5a-b0d4-72699e9da7bf.jpg)

ÍCONE: PROJETO 
https://www.flaticon.com/br/icone-gratis/solidariedade_5208516?related_id=5208516

**Comment by GabrielASMm** [comment]
ÍCONE: PRÁTICAS 
https://www.flaticon.com/br/icone-gratis/ecologia_2101777?related_id=2101777

![Image](https://user-images.githubusercontent.com/102264520/234978855-9b68d26f-73b0-431a-8c19-70edc5a25d7a.jpg)

**Comment by GabrielASMm** [comment]
![Image](https://user-images.githubusercontent.com/102264520/234979041-3fbc1d50-9ea4-4498-96e1-5cb78050895d.png)

ÍCONE: FECHAR ( X )

**Comment by GabrielASMm** [comment]
![Layout prática (14) (1)](https://user-images.githubusercontent.com/102264520/236566377-9b5c332d-250e-4e46-8bed-cd260c5c7b04.png)

Imagem na landing Page das práticas

**Comment by GabrielASMm** [comment]
![Layout prática (16)](https://user-images.githubusercontent.com/102264520/236566502-3e1f6107-fadf-40a9-b3e5-338657814c3b.png)

Imagem da barra de EXPLORAR das práticas na landing page

**Comment by PedroHNunesAlves** [comment]
![seta-para-cima](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/b4efb048-a1f2-468c-8bea-941154a690d8)

**Comment by PedroHNunesAlves** [comment]
![logout](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/d5a27e99-aa33-40d4-a678-626b6ce7a5ee)
https://icons8.com/icons/set/logout

**Comment by PedroHNunesAlves** [comment]
![avatar](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/226d7d9f-68f6-4cf5-90fd-da38fd910b5a)

**Comment by PedroHNunesAlves** [comment]
![alerta-7](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/957a73f3-93c4-4a65-9a88-9670b8044c9f)

**Comment by PedroHNunesAlves** [comment]
![estrela](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/50704f5c-62a9-4044-b750-b9c4a76e8527)

**Comment by PedroHNunesAlves** [comment]
![lixo](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/cee835e2-c3a7-4ea7-9536-19069fdc9c5d)

**Comment by PedroHNunesAlves** [comment]
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/dce67624-4d87-47a6-9664-cf635b4302d1)

**Comment by PedroHNunesAlves** [comment]
![comment](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/assets/127517961/f156c576-2a4b-471d-a177-09afca64d4e9)
