### ISSUE TITLE
Vetorizar Logotipo

### ISSUE THREAD

**Issue by VictorHVasquez** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local#9]
- [ ] Confeccionar um logotipo

- [ ] Submeter para aprovação do grupo

- [ ] Vetorizar

- [ ] Importar para o projeto

**Comment by VictorHVasquez** [comment]
@WesneyAndrade 
Por gentileza
Vetorize o Logo que você fez poste aqui em formato PNG com fundo transparente

**Comment by WesneyAndrade** [comment]
[Documentos Escaneados.pdf](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-1-e1-proj-web-t5-governanca-local/files/11278381/Documentos.Escaneados.pdf)
Logotipo iniciada para escolha de cores e finalização.

**Comment by WesneyAndrade** [comment]
![Image](https://user-images.githubusercontent.com/128436722/234152426-d911f255-2b4a-4477-9818-55c9555a5f27.png)

![Image](https://user-images.githubusercontent.com/128436722/234152424-74fa429b-6982-42b2-93ff-c76139820244.png)

![Image](https://user-images.githubusercontent.com/128436722/234152425-77230354-2b85-4b47-83b9-218c219db8aa.png)

![Image](https://user-images.githubusercontent.com/128436722/234152427-635f80e9-8e7c-4747-a3fd-a10c73b6d615.png)

artes inspiradas na logo desenhada para escolha final e vetorização

**Comment by WesneyAndrade** [comment]
![GL - Vetorizada](https://user-images.githubusercontent.com/128436722/234724914-6e5d3711-f001-4c06-8183-66de50f0bf36.svg)


Logo escolhida e vetorizada.
